package io.sytac.resumator.model.exceptions;

/**
 * Notifies an issue when trying to store an entity within a non-existent organization
 */
public class InvalidOrganizationException extends RuntimeException {
}
